FROM python:3.11-slim

WORKDIR /app

COPY  requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN useradd -m -u 1000 lucid-server

USER lucid-server

EXPOSE 8000

CMD ["python", "server.py"]
